{"name": "Проверка ответа на запрос аутентификации с неверным паролем", "status": "passed", "start": 1725695798287, "stop": 1725695798737, "uuid": "1b1f5812-d75f-462e-8fcb-9c891c46b0b9", "historyId": "7b59ea21293aa51d8fb438826b986f6c", "testCaseId": "7b59ea21293aa51d8fb438826b986f6c", "fullName": "tests.test_authentication.TestAuthentication#test_auth_with_wrong_passwd_expected_error", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_authentication"}, {"name": "subSuite", "value": "TestAuthentication"}, {"name": "host", "value": "DESKTOP-82VEM3U"}, {"name": "thread", "value": "8332-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_authentication"}]}